version: '3'

services:
  minecraft-docker-dir-watcher:
    image: ghcr.io/xyqyear/minecraft-docker-dir-watcher
    ports:
      - 8080:80
    volumes:
      - ./data:/data
      - ./example_server_dir:/watch
    restart: unless-stopped
