[tool.poetry]
name = "minecraft-docker-dir-watcher"
version = "0.0.1"
description = "a tool that watches a directory for new or removed minecraft docker containers."
authors = ["xyqyear <xyqyear@gmail.com>"]
readme = "README.md"
packages = [{ include = "minecraft_docker_dir_watcher" }]

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.8.5"
ruamel-yaml = "^0.17.32"
aiofiles = "^23.2.1"
aiosqlite = "^0.19.0"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
pytest = "^7.4.0"
coverage = "^7.3.0"
ipykernel = "^6.25.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
